name: Sync labels
on:
  push:
    branches:
      - master
    paths:
      - .github/labels.yml
      - .github/workflows/sync-labels.yml
  workflow_dispatch:

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
            TheBasedmint/basedmint-pm
            TheBasedmint/test1
            TheBasedmint/test2
            TheBasedmint/test3
          token: ${{ secrets.SYNC_LABELS2 }}
          prune: true