name: Read Labels

on:
  push:
    branches:
      - main

jobs:
  read_labels:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run read_labels script
      run: python .github/scripts/read_labels.py
      env:
        GITHUB_TOKEN: ${{ secrets.SYNC_LABELS2 }}
