name: Restore Labels Workflow

on:
  push:
    branches:
      - main

jobs:
  restore-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run restore_labels.py
        run: python .github/scripts/restore_labels.py

      - name: Upload issue events as artifact
        uses: actions/upload-artifact@v2
        with:
          name: issue-events
          path: output/*.json
          if-no-files-found: warn
