name: Retrieve Deleted Label Info
on:
  workflow_dispatch:  # Manual trigger

jobs:
  retrieve-deleted-label:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve deleted label info
      id: print-label-info
      run: |
        TOKEN=${{ secrets.SYNC_LABELS2 }}
        ORG_NAME="TheBasedmint"
        LABEL_NAME="Marketplace"  # Replace with the label name you want to retrieve

        # GraphQL query to fetch label removal events
        query='
          query {
            organization(login: "'$ORG_NAME'") {
              auditLog(userLogin: "'$LABEL_NAME'", first: 10) {
                edges {
                  node {
                    ... on OrgRemoveMemberAuditEntry {
                      createdAt
                      actor {
                        login
                      }
                      ... on OrgRemoveMemberAuditEntry {
                        actor {
                          login
                        }
                      }
                      ... on OrgRemoveOutsideCollaboratorAuditEntry {
                        actor {
                          login
                        }
                      }
                      ... on OrgRemoveOutsideCollaboratorAuditEntry {
                        actor {
                          login
                        }
                      }
                      ... on OrgRemoveBillingManagerAuditEntry {
                        actor {
                          login
                        }
                      }
                      ... on OrgRemoveOutsideCollaboratorAuditEntry {
                        actor {
                          login
                        }
                      }
                      ... on OrgRemoveOutsideCollaboratorAuditEntry {
                        actor {
                          login
                        }
                      }
                      ... on OrgRemoveOutsideCollaboratorAuditEntry {
                        actor {
                          login
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        '

        # Fetch label removal events using GraphQL
        label_events=$(curl -v -s -X POST -H "Authorization: Bearer $TOKEN" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{"query":"'$query'"}' \
          "https://api.github.com/graphql" | jq -r '.')

        # Print label events
        echo "GraphQL Response:"
        echo "$label_events"

        # Save retrieved label info
        deleted_label_info=$(echo "$label_events")
        echo "Deleted Label Info: $deleted_label_info" > deleted-label-info.txt

        # Print the contents of the file
        cat deleted-label-info.txt

    - name: Output label info
      run: echo "deleted_label_info=${{ steps.print-label-info.outputs.deleted_label_info }}"

    - name: Upload deleted-label-info as artifact
      uses: actions/upload-artifact@v2
      with:
        name: deleted-label-info
        path: deleted-label-info.txt
